Quiz App
GulcinGulcu/Projects pull request #12
Opened 2024-02-08 13:11 UTC by GulcinGulcu

2024-02-09 20:37 UTC, annasvst requested changes

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/HomePage/styles.css
> +    background-color: #4D5B9E;
Add variables for all colors in the index.css file (:root selector) and refer to variables when you need to use a color. This would make the code easier to maintain.

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/QuizPage/index.jsx
> +                questions.map((question, i) => (
You need to add 'key' property to elements in react when you create a dynamic list like here. Using index and as a key is not preferable. Instead, you can use text of the question with all spaces removed, for example.
Something like this should work
```
<fieldset className="question-block" key={question[0].replaceAll(' ', '')}>
```

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/QuizPage/index.jsx
> +                            question.map(answer => (
There's a problem with a type of the questions state. It's an array with two arrays inside of it:
```
[
["Question text"],
["Answer1", "Answer2", "Answer3,"Answer4"]
]
```
When you see a structure like this, use an object instead as you can easily refer to object's keys and be sure about what the value format will be.

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/QuizPage/index.jsx
> +                                                            name={i}
Name of an input should not be an index, instead, you can set it to the question text with the spaces removed.
In this application, it get complicated to work with the data as it does not have ids. You could add ids to the data that you fetch from the api and store it with ids (e.g. use Date.now() to generate a timestamp that can be use as id here).

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/QuizPage/index.jsx
> +    const [questions, setQuestions] = useState([]);
It should be enough to have questionData from the context, no need to add it to a state here. Actually, the entire useEffect function is not needed. Just use data from the questionData directly (make sure it has ids added before you store it in context). 
So, remove questions and correctAnswersData states.

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/Components/QuizPage/index.jsx
> +    const [bgColor, setBgColor] = useState('');
I this the format of `bgColor` is not very suitable for current situation. You have multiple questions and answers, their background can be different at the same point in time. Instead, you could just add class 'correct' and 'incorrect' to the answers once the entire quiz is submitted. Background should be added for these classes in CSS in this case.
You may also want to add 'selected' class (or similar) to the answer that was clicked on.

2024-02-09 20:37 UTC, annasvst commented on QuizAppProject/src/modules/fetchQuestions/index.jsx
> +export const QuestionProvider = ({ children }) => {
It's better not to fetch data in the provider component. Provider is for storing the data and defining the way in which it should be updated. 

Think about QuestionProvider (and similar providers) as a storage. The storage keeps the products and can have some rules about how they should be stored (e.g. what product should be o which shelf etc.).However, the storage should not get the products from a factory, it should not produce products, etc. It should only case about storing them and setting rules for storage.

Take a look at the provider that we did in the lesson and try to implement a similar solution instead if you want to use context here. However, it's only QuizPage component that uses data so normally you don't even need context provider in this case.

2024-02-09 22:41 UTC, GulcinGulcu commented on QuizAppProject/src/App.css
> +  height: 100%;
I was going to ask that, thank you.

2024-02-09 22:42 UTC, GulcinGulcu commented on QuizAppProject/src/App.js
> +import { useState, useEffect, useRef } from 'react';
I forgot to delete them :)

2024-02-24 21:36 UTC, annasvst approved these changes
Well done! 👏

2024-03-05 09:02 UTC, merged